version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - internal_network
    environment:
      # you can remove the relay if you setup your own smtp
      RELAY_HOST: ${RELAY_HOST}
      RELAY_PORT: ${RELAY_PORT}
      RELAY_USERNAME: ${RELAY_USER}
      RELAY_PASSWORD: ${RELAY_PASSWORD}
  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=plausible
    networks:
      - internal_network
  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - internal_network
  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - ${PORT}:8000
    networks:
      - internal_network
      - traefik_network 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.entrypoints=http"
      - "traefik.http.routers.plausible.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.plausible-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plausible.middlewares=plausible-https-redirect"
      - "traefik.http.routers.plausible-secure.entrypoints=https"
      - "traefik.http.routers.plausible-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.plausible-secure.tls=true"
      - "traefik.http.routers.plausible-secure.tls.certresolver=http"
      - "traefik.http.routers.plausible-secure.service=plausible"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000" #must match the inner port
      - "traefik.traefik_network.passHostHeader=true"
      - "traefik.docker.network=traefik_network"
    environment:
      - ADMIN_USER_EMAIL=${ADMIN_USER_EMAIL}
      - ADMIN_USER_NAME=${ADMIN_USER_NAME}
      - ADMIN_USER_PWD=${ADMIN_PASSWORD}
      - BASE_URL=https://${DOMAIN}
      - HOST=${DOMAIN}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
  
networks:
  internal_network:
  traefik_network:
      external: true  
