version: '3'
services:
  database:
    container_name: postgres_${DOCKER_IMAGE_PREFIX}
    image: postgres:14
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - internal_network
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: '${PASSWORD}'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache_directus_${DOCKER_IMAGE_PREFIX}
    image: redis:6
    networks:
      - internal_network

  directus:
    container_name: directus_${DOCKER_IMAGE_PREFIX}
    image: directus/directus:latest
    ports:
      - 8055:8055
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directus.entrypoints=http"
      - "traefik.http.routers.directus.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.directus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.directus.middlewares=directus-https-redirect"
      - "traefik.http.routers.directus-secure.entrypoints=https"
      - "traefik.http.routers.directus-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.directus-secure.tls=true"
      - "traefik.http.routers.directus-secure.tls.certresolver=http"
      - "traefik.http.routers.directus-secure.service=directus"
      - "traefik.http.services.directus.loadbalancer.server.port=8055"
      - "traefik.docker.network=traefik_network"
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    
    networks:
      - internal_network
      - traefik_network
    depends_on:
      - cache
      - database
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: '${PASSWORD}'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '${EMAIL}'
      ADMIN_PASSWORD: '${PASSWORD}'

      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      PUBLIC_URL: 'https://${DOMAIN}'

networks:
  internal_network:
  traefik_network:
    external: true