version: '3.9'

services:
    database:
        container_name: postgres_${DOMAIN}
        image: postgres:14
        restart: always 
        ports: 
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - internal_network
            - traefik_network
        environment:
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
    # https://github.com/heyman/postgresql-backup    
    postgres_backup:
        restart: always 
        container_name: postgres_backup_${DOMAIN}
        build: ./postgres_backup
        networks:
            - internal_network
        environment:
            CRON_SCHEDULE: '15 3 * * *' # every day at 3:15am
            DB_HOST: 'database'
            DB_PASS: '${DB_PASSWORD}'
            DB_USER: '${DB_USER}'
            DB_NAME: '${DB_NAME}'
            S3_PATH: '${S3_PATH}'
            AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
            AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
            AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION}'
            MAIL_T0: '${MAIL_TO}'
            MAIL_FROM: '${MAIL_FROM}'
    sveltekit:
        container_name: sveltekit_${DOMAIN}
        build: ./app
        ports: 
            - "${SVELTEKIT_PORT}:3000"
        restart: always 
        networks:
            - traefik_network
        labels:
            - "traefik.enable=true"
            # redirect http traffic to https
            - "traefik.http.routers.sveltekit.entrypoints=http"
            # this rule redirects both the root domain and the www subdomain
            - "traefik.http.routers.sveltekit.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
            # uncomment if you don't want to add the www subdomain and comment out above line.
            #- "traefik.http.routers.sveltekit.rule=Host(`${DOMAIN}`)"
            - "traefik.http.middlewares.sveltekit-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.sveltekit.middlewares=sveltekit-https-redirect"
            # setup https domain to forward to container
            - "traefik.http.routers.sveltekit-secure.entrypoints=https"
            # this rule redirects both the root domain and the www subdomain
            - "traefik.http.routers.sveltekit-secure.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
            # uncomment if you don't want to add the www subdomain and comment out above line.
            # - "traefik.http.routers.sveltekit-secure.rule=Host(`${DOMAIN}`)"
            # setup our ssl certificate
            - "traefik.http.routers.sveltekit-secure.tls=true"
            - "traefik.http.routers.sveltekit-secure.tls.certresolver=http"
            - "traefik.http.routers.sveltekit-secure.service=sveltekit"
            # tell traefik where our container internal port is
            - "traefik.http.services.sveltekit.loadbalancer.server.port=3000" 
            # tell traefik what network we are using
            - "traefik.docker.network=traefik_network"
volumes:
    postgres-data:
networks:
  traefik_network:
    external: true