version: '3.8'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${DOMAIN} # set to fqdn of host
    networks:
      - traefik_network
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.entrypoints=http"
      - "traefik.http.routers.netdata.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.netdata-auth.basicauth.users=${USER_PASSWORD_PAIR}"
      - "traefik.http.middlewares.netdata-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.netdata.middlewares=netdata-https-redirect"
      - "traefik.http.routers.netdata-secure.entrypoints=https"
      - "traefik.http.routers.netdata-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.netdata-secure.middlewares=secHeaders@file,netdata-auth"
      - "traefik.http.routers.netdata-secure.tls=true"
      - "traefik.http.routers.netdata-secure.tls.certresolver=http"
      - "traefik.http.routers.netdata-secure.service=netdata"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.docker.network=frontend"
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
networks:
  traefik_network:
    external: true